posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [

    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('<int:id>/', views.show, name="show"),
    path('update/<int:id>/', views.update, name="update"),
    path('delete/<int:id>/', views.delete, name="delete"),
    path('<int:id>/new_comment/', views.new_comment, name="new_comment"),
    path('<int:id>/create_comment/', views.create_comment, name="create_comment"),
    path('<int:id>', views.delete_comment, name="delete_comment"),
    path('favourite/', views.favourite, name="favourite"),
    path('<int:id>/like/', views.like, name="like"),
]

sns/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('<int:id>/follow_toggle/', follow_toggle, name="follow_toggle"),
]

posts/models.py
from django.db import models

# Create your models here.
from django.db import models
from django import forms
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="img/", blank = True)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    likes = models.ManyToManyField(User, related_name='likes')    
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    objects = models.Manager()
    content = models.TextField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name='comments')
    # Post의 Comment, Comment의 Post를 서로 추적 가능
    
    created_at = models.DateTimeField(auto_now_add=True)
        
        

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import *
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):
    image = ImageField(_("Image of User"), upload_to="img/", default="none/default_profile.jpg")
    followings = ManyToManyField("self", related_name='followers', symmetrical=False)

posts/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'photo'
        ]
        labels = {
            'title': "제목",
            'content': "내용",
            'photo' : "사진"
        }
        


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        labels = {
            'content': "내용",
        }
        

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.models import User

# Create your views here.

def new(request):
    return render(request, 'posts/new.html')

def create(request):
    form = PostForm()
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False) # form을 당장 저장하지 않음. 데이터 저장 전 뭔가 하고 싶을 때 사용.
            form.user = request.user
            form.save()
            return redirect('home')
    return render(request, 'posts/create.html', {'form': form})

def show(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'posts/show.html', {"post": post})
    
def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        title = request.POST.get('title')
        content = request.POST.get('content')
        photo = request.POST.get('photo')
        post.title = title
        post.content = content
        post.photo = photo
        post.save()
        return redirect('posts:show', post.id)
    return render(request, 'posts/update.html', {"post": post})
    
def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect('home')
    
# Comment


def new_comment(request, id):
    post = get_object_or_404(Post, pk=id)
    return render(request, 'posts/new_comment.html', {'post': post})
    
    
def create_comment(request, id):
    form = CommentForm()
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('posts:show', post.id)
    return render(request, 'posts/new_comment.html', {'form': form})
        
        
def delete_comment(request, id):
    comment = get_object_or_404(Comment, pk=id)
    post = comment.post
    comment.delete()
    return render(request, 'posts/show.html', {"post": post})
    

def favourite(request):
    user = request.user
    my_posts = user.likes.all()
    return render(request, 'posts/favourite.html', {'posts': my_posts})

   
def like(request, id):
    user = request.user #로그인한 유저를 가져옴
    post = get_object_or_404(Post, pk=id)
    if request.method == 'POST':
        if post.likes.filter(id = user.id).exists(): #해당 post에 로그인한 유저가 like 컬럼에 존재하면
            post.likes.remove(user) #like 컬럼에서 해당 유저를 지운다.
        else:
            post.likes.add(user) #그 외의 경우 추가한다.
    return redirect('posts:show', post.id)    
        

sns/views.py
from django.shortcuts import render
from posts .models import Post

def home(request):
    posts = Post.objects.all()
    return render(request, 'home.html', {"posts": posts})

users/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from .models import User


def follow_toggle(request, id):
    user = request.user
    if user.is_anonymous:
        return redirect('account_login')
    followed_user = get_object_or_404(User, pk=id)

    is_follower = user in followed_user.followers.all()

    if is_follower:
        user.followings.remove(followed_user)
    else:
        user.followings.add(followed_user)

    return redirect('home')

posts/templates/posts/favourite.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'home' %}"><img src = "http://mblogthumb1.phinf.naver.net/20160709_244/wehira_1468076100396tPA5u_JPEG/%BF%A1%B6%D9%B5%E5%C7%CF%BF%EC%BD%BA_%BC%F6%BA%D0%B0%A1%B5%E6_%C4%DD%B6%F3%B0%D5_%BF%F6%C5%CD_%C1%A9%B8%AE_%C5%A9%B8%B2_%B5%B5%B8%AE%B8%A6_%C3%A3%BE%C6%BC%AD_00011.JPG?type=w800" width = 50 height = 50 /></a>
<br><br>

    {% for post in posts %}

          <a href="{% url 'posts:show' post.id %}"><h5 style="font-family: 'LotteMartHappy'">#{{ post.id }}번째 니모: {{ post.title }}</h5></a><br><br>
          <h6 style="font-family: 'LotteMartDream'" class="card-subtitle mb-2 text-muted">작성자: {{ post.user }}</h6>
          <p style="font-family: 'LotteMartDream'" class="card-text">{{ post.content }}</p>

    {% endfor %}    
    </div>
</div>

{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'home' %}"><img src = "http://mblogthumb1.phinf.naver.net/20160709_244/wehira_1468076100396tPA5u_JPEG/%BF%A1%B6%D9%B5%E5%C7%CF%BF%EC%BD%BA_%BC%F6%BA%D0%B0%A1%B5%E6_%C4%DD%B6%F3%B0%D5_%BF%F6%C5%CD_%C1%A9%B8%AE_%C5%A9%B8%B2_%B5%B5%B8%AE%B8%A6_%C3%A3%BE%C6%BC%AD_00011.JPG?type=w800" width = 50 height = 50 /></a>
       <h3 style = "font-family: 'yg-jalnan'">새글 작성하기</h3>
        
        <form action="{% url 'posts:create' %}" method="POST">
            {% csrf_token %}
            <labe style = "font-family: 'S-CoreDream-3Light'">글의 제목</labe><br>
            <input style = "font-family: 'S-CoreDream-3Light'" type="text" name="title"><br>
 
            <label style = "font-family: 'S-CoreDream-3Light'">글의 내용</label><br>
            <textarea style = "font-family: 'S-CoreDream-3Light'" name="content"></textarea><br>
            
            <input style = "font-family: 'S-CoreDream-3Light'" type="submit" value="글쓰기">
        </form>



{% endblock %}

posts/templates/posts/new_comment.html
{% extends 'base.html' %}
{% block content %}
<h1>댓글 달기</h1>
<form action="{% url 'posts:new_comment' post.id %}" method="POST">
    {% csrf_token %}
    <label>댓글 내용</label><br>
    <textarea name="content"></textarea><br>
    
    <input type="submit" value="댓글쓰기">
</form>
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}
<br><br>
<div class = "box" style = "text-align:center">
    
    {% if post.photo %}
        <img src = "{{ post.photo.url }}" style ="width: 350px; height: 350px"/>
    {% endif %}
<br><br>
    <h2>댓글</h2>
    <p>댓글 수 : {{ post.comments.count }}개</p> <!-- related_name을 써서 가능한 부분 -->
    <a href="{% url 'posts:new_comment' post.id %}">댓글 남기기</a> <!-- url 클릭 시 post.id를 함께 넘겨줌 -->
    {% for comment in post.comments.all %}
        <p>쓰니 : {{ comment.username }}</p>
        <p>내용 : {{ comment.content }}</p>
        {% empty %}
        <p>댓글이 없습니다.</p>
    {% endfor %}
        <a style = "font-family: 'S-CoreDream-3Light'; border: 2px solid;" class="btn btn-outline-success" href="{% url 'posts:update' post.id %}"><strong>수정</strong></a>
        <a style = "font-family: 'S-CoreDream-3Light'; border: 2px solid;" class="btn btn-outline-success" href="{% url 'posts:delete' post.id %}" data-method="POST"><strong>삭제</strong></a>
        <br>    
</div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'home' %}"><img src = "http://mblogthumb1.phinf.naver.net/20160709_244/wehira_1468076100396tPA5u_JPEG/%BF%A1%B6%D9%B5%E5%C7%CF%BF%EC%BD%BA_%BC%F6%BA%D0%B0%A1%B5%E6_%C4%DD%B6%F3%B0%D5_%BF%F6%C5%CD_%C1%A9%B8%AE_%C5%A9%B8%B2_%B5%B5%B8%AE%B8%A6_%C3%A3%BE%C6%BC%AD_00011.JPG?type=w800" width = 50 height = 50 /></a>

        <form action="{% url 'posts:update' post.pk %}" method="POST">
            {% csrf_token %}
            <h3 style = "font-family: 'yg-jalnan'">수정하기</h3>
            <label style = "font-family: 'S-CoreDream-3Light'">글의 제목</labe><br>
            <input style = "font-family: 'S-CoreDream-3Light'" type="text" name="title" value="{{ post.title }}"><br>
            
            <label style = "font-family: 'S-CoreDream-3Light'">글의 내용</label><br>
            <textarea style = "font-family: 'S-CoreDream-3Light'" name="content">{{ post.content }}</textarea><br>
            
            <input style = "font-family: 'S-CoreDream-3Light'" class="btn btn-primary" type="submit" value="수정">
        </form>




{% endblock %}

templates/base.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>강릉여은파</title>
  </head>
  <body>
    <div class="w3-container" style="background:#9e91f2">
      <h1 style = "font-family : 'TmonMonsori'; color: white;"><br>6월, 그녀들의 여은파그램</h1>
      <h3 style = "font-family: 'S-CoreDream-3Light'; color: white;"></h3><br>
      <p style = "font-family: 'S-CoreDream-3Light'; color: white;">강릉종강파티. 지금 시작합니다.</p>   
    </div>
  
    <style>
      /*body{*/
      /*  background-image: url('https://cdn.shopify.com/s/files/1/1195/0530/products/unnamed_1_a19bd10c-c061-4673-bcc9-9d414ff93fde.jpg?v=1539213826');*/
      /*  background-size: 150px;*/
      /*}*/
      @font-face { font-family: 'yg-jalnan'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff'); font-weight: normal; font-style: normal; }
      @font-face { font-family: 'S-CoreDream-3Light'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_six@1.2/S-CoreDream-3Light.woff') format('woff'); font-weight: normal; font-style: normal; } 
      @font-face { font-family: 'LotteMartDream'; font-style: normal; font-weight: 400; src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamMedium.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamMedium.woff') format('woff'); } @font-face { font-family: 'LotteMartDream'; font-style: normal; font-weight: 700; src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamBold.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamBold.woff') format('woff'); } @font-face { font-family: 'LotteMartDream'; font-style: normal; font-weight: 300; src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamLight.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartDream/LotteMartDreamLight.woff') format('woff'); } .lottemartdream * { font-family: 'LotteMartDream', sans-serif; }
      @font-face { font-family: 'LotteMartHappy'; font-style: normal; font-weight: 400; src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartHappy/LotteMartHappyMedium.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartHappy/LotteMartHappyMedium.woff') format('woff'); } @font-face { font-family: 'LotteMartHappy'; font-style: normal; font-weight: 700; src: url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartHappy/LotteMartHappyBold.woff2') format('woff2'), url('//cdn.jsdelivr.net/korean-webfonts/1/corps/lottemart/LotteMartHappy/LotteMartHappyBold.woff') format('woff'); } .lottemarthappy * { font-family: 'LotteMartHappy', sans-serif; }   
      @font-face { font-family: 'SDKukdetopokki'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/SDKukdetopokki.woff') format('woff'); font-weight: normal; font-style: normal; }
      @font-face { font-family: 'TmonMonsori'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/TmonMonsori.woff') format('woff'); font-weight: normal; font-style: normal; }
     </style>

{% block content %}
    
{% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
            {% csrf_token %}
{% if user.is_authenticated %}
<div style="text-align:right">
    안녕 {{ user.username }}!
  <a href="{% url 'account_logout' %}"> / logout</a><br><br>
  <a href="{% url 'posts:new' %}">새 글 쓰기</a>
  <br><br><br>
</div>

<div class="container">
  <div class="row">
    {% for post in posts %}
    
    <div class="col-sm" align="center" style="padding-bottom: 35px;">
      <a href="{% url 'posts:show' post.id %}">
        {% if post.photo %}
          <img src = "{{ post.photo.url }}" style ="width: 250px; height: 250px"/>
        {% endif %}
      </a>
    </div>
    {% empty %}
    <p>글이 없습니다.</p>
    {% endfor %}
  </div>
</div>

{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'account_login' %}">login</a>
{% endif %}

{% endblock %}